filebeat.inputs:
  # Application logs from microservices (JSON format)
  - type: log
    enabled: true
    paths:
      - /app/logs/*/*.json
    fields:
      log_type: application_json
      source_type: application
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  # Application logs from microservices (plain text format) - /app/logs path
  - type: log
    enabled: true
    paths:
      - /app/logs/*/*.log
    fields:
      log_type: application_text
      source_type: application
    fields_under_root: true
    multiline.pattern: '^\d{2}-\d{2}-\d{4} \d{2}:\d{2}:\d{2}'
    multiline.negate: true
    multiline.match: after
    processors:
      - add_fields:
          target: ''
          fields:
            service_name: '${HOSTNAME:unknown}'

  # Application logs from microservices (plain text format) - /logs path
  - type: log
    enabled: true
    paths:
      - /logs/*/*.log
    fields:
      log_type: application_text
      source_type: application
    fields_under_root: true
    multiline.pattern: '^\d{2}-\d{2}-\d{4} \d{2}:\d{2}:\d{2}'
    multiline.negate: true
    multiline.match: after
    processors:
      - add_fields:
          target: ''
          fields:
            service_name: '${HOSTNAME:unknown}'

  # Docker container logs
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

# Processors to enrich logs
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

# Output configuration
output.logstash:
  hosts: ["opensearch-logstash:5044"]

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
