apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: connections-db
  name: connections-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: connections-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: connections-db
    spec:
      containers:
        - env:
            - name: NEO4J_AUTH
              value: neo4j/password
          image: neo4j
          name: connections-db
          ports:
            - containerPort: 7474
              protocol: TCP
            - containerPort: 7687
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: connections-db-data
      restartPolicy: Always
      volumes:
        - name: connections-db-data
          persistentVolumeClaim:
            claimName: connections-db-data
