apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: discovery-server
    spec:
      containers:
        - image: premtsd18/discovery-server
          name: discovery-server
          ports:
            - containerPort: 8761
              protocol: TCP
          volumeMounts:
            - mountPath: /logs/discovery-server
              name: discovery-server-claim0
      restartPolicy: Always
      volumes:
        - name: discovery-server-claim0
          persistentVolumeClaim:
            claimName: discovery-server-claim0
