apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /app/logs/*/*.log  # Mount log file location
        fields:
          service: linkedin-microservice
        fields_under_root: true
        multiline.pattern: '^\d{2}-\d{2}-\d{4}'  # For multiline logs
        multiline.negate: true
        multiline.match: after

    output.logstash:
      hosts: ["logstash:5044"]
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: filebeat
  name: filebeat-cm0
