apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: kafbat-ui
  name: kafbat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafbat-ui
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: kafbat-ui
    spec:
      containers:
        - env:
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka:9092
            - name: KAFKA_CLUSTERS_0_NAME
              value: local
          image: ghcr.io/kafbat/kafka-ui:latest
          name: kafbat-ui
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
