apiVersion: v1
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      json {
        source => "message"
        skip_on_invalid_json => true
      }
    }

    output {
      stdout { codec => rubydebug }

      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "linkedin-logs-%{+YYYY.MM.dd}"
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: logstash
  name: logstash-cm0
