apiVersion: v1
kind: Secret
metadata:
  name: linkedin-secrets
  namespace: linkedin-prod
type: Opaque
stringData:
  DB_PASSWORD: "linkedin_prod_password"
  REDIS_PASSWORD: "redis_prod_secret"
  NEO4J_PASSWORD: "neo4j_prod_password"
  JWT_SECRET: "linkedin-prod-jwt-secret-key-minimum-32-characters-long"
