apiVersion: v1
kind: Secret
metadata:
  name: linkedin-secrets
  namespace: linkedin-prod
type: Opaque
stringData:
  POSTGRES_PASSWORD: "password"
  DB_PASSWORD: "password"
  REDIS_PASSWORD: "secret123"
  NEO4J_AUTH: "neo4j/neo4j_prod_password"
  NEO4J_PASSWORD: "neo4j_prod_password"
  JWT_SECRET: "linkedin-super-secret-jwt-key-min-32-characters-long"
  GIT_PASSWORD: "glpat-g9sdZXeePqZ3STf9sB9uAW86MQp1OjFtdAk.01.0z0ntlpwu"
