apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - image: premtsd18/user-service
          name: user-service
          ports:
            - containerPort: 9020
              protocol: TCP
          volumeMounts:
            - mountPath: /app/logs/user-service
              name: user-service-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: user-service-cm0
          name: user-service-cm0
