apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  ports:
    - name: "9020"
      port: 9020
      targetPort: 9020
  selector:
    io.kompose.service: user-service
