# Traefik Static Configuration
# This file contains the main Traefik configuration

# API and Dashboard configuration
api:
  dashboard: true
  insecure: true  # Set to false in production

# Entry Points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        options: default

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: linkedin-network

  file:
    directory: /etc/traefik/dynamic
    watch: true

# Certificate Resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      email: i.prem.tsd@outlook.com
      storage: /letsencrypt/acme.json
      tlsChallenge: {}
      # Use HTTP challenge for development/testing
      # httpChallenge:
      #   entryPoint: web

  # For wildcard certificates (requires DNS challenge)
  letsencrypt-dns:
    acme:
      email: i.prem.tsd@outlook.com
      storage: /letsencrypt/acme-dns.json
      dnsChallenge:
        provider: cloudflare  # Change to your DNS provider
        delayBeforeCheck: 30
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# Logging
log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

# Metrics (optional)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# TLS Options
tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
      sniStrict: true

# Pilot (optional - for Traefik Cloud)
# pilot:
#   token: "your-pilot-token"
